name: CI

on:
  push:
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      # TODO automate building
      - name: setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: v17.3.0
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      # TODO automate testing
      - name: setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: v17.3.0
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npx jest
